### PR TITLE
Upgrade broken prettier workflow version

### PR DESCRIPTION
**Pull request by sonkkeli**
I wonder if I should rather point this to master instead of a specific version though?

### CODE REVIEW

**Comment by cmfcmf** [comment]
Maybe set it to `@v4` instead, so that we get future bug fixes and updates, but no breaking changes should they eventually release `v5`?

**Comment by sonkkeli** [comment]
> Maybe set it to `@v4` instead, so that we get future bug fixes and updates, but no breaking changes should they eventually release `v5`?

It doesn't seem to support this kind of version setting, seems to be either everything or nothing :/

**Comment by cmfcmf** [comment]
Ah, I remember, I think we ran into this before. It looks like the action would need to create and manage a separate `v4` tag for it to work: https://docs.github.com/en/actions/creating-actions/about-custom-actions#using-tags-for-release-management. IMHO going with hard-coding `@v4.3` then is the best option.

**Review by cmfcmf — APPROVED** [review]
I'll leave the decision of whether to use `master` or `v4.3` up to you.

**Comment by sonkkeli** [comment]
> Ah, I remember, I think we ran into this before. It looks like the action would need to create and manage a separate `v4` tag for it to work: https://docs.github.com/en/actions/creating-actions/about-custom-actions#using-tags-for-release-management. IMHO going with hard-coding `@v4.3` then is the best option.

Yeah I agree, better safe than sorry.

**Pull request merged**
